---
title: "March Madness 2018 EDA"
author: "Jacob Dym, Paul Harmon"
date: "February 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Data files
```{r}
# Note this wd setup work only if the current working directory is the MARCHMADNESS folder
#Paul: If on P$'s computer, don't run the next line of code
work <- getwd()
n <- nchar(work)
work <- substr(work, 1, n - 13)
setwd(paste0(work, "/DataFiles"))

# Load DataFiles
Cities <- read.csv("Cities.csv")
Conferences <- read.csv("Conferences.csv")
ConferenceTourneyGames <- read.csv("ConferenceTourneyGames.csv")
GameCities <- read.csv("GameCities.csv")
NCAATourneyCompactReults <- read.csv("NCAATourneyCompactResults.csv")
NCAATourneyDetailedResults <- read.csv("NCAATourneyDetailedResults.csv")
NCAATourneySeedRoundSlots <- read.csv("NCAATourneySeedRoundSlots.csv")
NCAATourneySeeds <- read.csv("NCAATourneySeeds.csv")
NCAATourneySlots <- read.csv("NCAATourneySlots.csv")
RegularSeasonCompactResults <- read.csv("RegularSeasonCompactResults.csv")
RegularSeasonDetailedResults <- read.csv("RegularSeasonDetailedResults.csv")
Seasons <- read.csv("Seasons.csv")
SecondaryTourneyCompactResults <- read.csv("SecondaryTourneyCompactResults.csv")
SecondaryTourneyTeams <- read.csv("SecondaryTourneyTeams.csv")
TeamCoaches <- read.csv("TeamCoaches.csv")
TeamConferences <- read.csv("TeamConferences.csv")
Teams <- read.csv("Teams.csv")
TeamSpellings <- read.csv("TeamSpellings.csv")
```

# EDA
```{r}
library(ggplot2)
library(dplyr)
# Add descriptions to ConferencesTourneyGames
Conferences <- left_join(ConferenceTourneyGames, Conferences, "ConfAbbrev")
rm(ConferenceTourneyGames)

# Look at 2017 NCAA tournament
tournament_2017 <- NCAATourneyCompactReults[NCAATourneyCompactReults$Season == 2017, ]
tournament_2017$WTeamID <- as.factor(tournament_2017$WTeamID)
dim(tournament_2017) # Verify there are 67 games
ggplot(tournament_2017) + geom_bar(aes(WTeamID), fill = "orange") + theme_bw() # Verify the number of wins (6-7 for first place)

# Look at teams proportion of wins in the regular season and if they make it to the tournament
RegularSeasonSub <- list()
for(i in 1985:2017){
  RegularSeasonSub[[i - 1984]] <- subset(RegularSeasonCompactResults, Season == i)
}

# Look at 2017 season
teams2017 <- unique(c(RegularSeasonSub[[33]]$WTeamID, RegularSeasonSub[[33]]$LTeamID))
length(teams2017) # Number of teams in 2017
NumWins2017 <- NumLoss2017 <- InTourney <- c()
for(i in 1:length(teams2017)){
  NumWins2017[i] <- sum(RegularSeasonSub[[33]]$WTeamID == teams2017[i])
  NumLoss2017[i] <- sum(RegularSeasonSub[[33]]$LTeamID == teams2017[i])
  InTourney[i] <- teams2017[i] %in% tournament_2017$WTeamID | teams2017[i] %in% tournament_2017$LTeamID
}
WinProp2017 <- data.frame(Team = teams2017, Wins = NumWins2017 / (NumWins2017 + NumLoss2017), InTournament = InTourney)

# Plot win proportions
ggplot(WinProp2017) + geom_bar(aes(Team, Wins, fill = InTournament), stat = "identity") + theme_bw()
```
It looks like teams with the highest win rate aren't always in the tournament. This is expected because the teams that get into the tournament are either from at-large bids or they win their conference tournament. (Teams with lower win counts probably got in by winning a conference tournament. )

# Set up for ELO
```{r}
# Construct data frames for individual teams to be used for ELO calculations
Team_ELO <- list()
for(i in 1:dim(Teams)[1]){
  dat <- RegularSeasonCompactResults[RegularSeasonCompactResults$WTeamID == Teams$TeamID[i] |
                                       RegularSeasonCompactResults$LTeamID == Teams$TeamID[i], ]
  win <- dat$WTeamID == Teams$TeamID[i]
  season <- dat$Season
  coach <- TeamCoaches[TeamCoaches$TeamID == Teams$TeamID[i], ]
  coach <- coach[coach$FirstDayNum == 0, ]
  dat <- full_join(dat, coach, by = "Season")
  dat <- dat[dat$Season != 2018, ]
  home <- dat$WLoc
  for(j in 1:length(home)){
    if(win[j]){
      home[j] <- home[j]
      next
    }
    if(!win[j]){
      if(home[j] == "N"){
        home[j] <- home[j]
        next
      }
      else home[j] <- "A"
    }
  }
  ot <- dat$NumOT
  game <- data.frame(wt = dat$WTeamID, lt = dat$LTeamID)
  gselect <- game != Teams$TeamID[i]
  opponent <- c()
  for(j in 1:dim(game)[1]){
    opponent[j] <- game[j, gselect[j, ]] 
  }
  opteam <- c()
  for(j in 1:length(opponent)){
    opteam[j] <- as.character(Teams$TeamName[Teams$TeamID == opponent[j]])
  }
  score_difference <- as.numeric(win) * (dat$WScore - dat$LScore) + as.numeric(!win) * (dat$LScore - dat$WScore)
  elo <- c(1000, rep(0, length(win) - 1))
  Team_ELO[[i]] <- data.frame(TeamName = Teams$TeamName[i], TeamID = Teams$TeamID[i], 
                              Season = season, Win = win, PointSpread = score_difference, Location = home,
                              OvertimeRounds = ot, Coach = dat$CoachName, OpponentID = opponent, 
                              Opponent = opteam, Day = dat$DayNum, ELO = elo) 
}

# Function to calculate a teams new ELO rating based on a game
Get_ELO <- function(k, df, teamid, iter){
  tdat <- df[[which(Teams$TeamID == teamid)]][iter - 1, ]
  Current_ELO <- tdat$ELO
  opid <- tdat$OpponentID
  odat <- df[[which(Teams$TeamID == opid)]]
  pos <- which((odat$Day == tdat$Day) & (odat$TeamID == tdat$OpponentID) & (odat$Season == tdat$Season))
  Opponent_ELO <- odat[pos - 1, ]$ELO
  w <- as.numeric(tdat$Win)
  dr <- Current_ELO + 100 * (tdat$Location == "H") - (Opponent_ELO + 100 * (odat$Location == "H"))
  we <- 1 / (10 ^(-dr / 400) + 1)
  elo <- Current_ELO + k * abs(tdat$PointSpread) * (w - we)
  return(elo)
}
```

# Build ELO scores
```{r}
for(i in 2:101){
  Team_ELO[[1]]$ELO[i] <- Get_ELO(20, Team_ELO, 1101, i) 
}
```



#PLOT SOME ELOS BOIIII 
```{r}

```








